import type { ExtensionAPI } from '@earendil-works/pi-coding-agent'

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

/** Short whimsical messages shown in Pi's working row while the agent is streaming. */
const WORKING_MESSAGES = [
    'Schlepping...',
    'Combobulating...',
    'Doing...',
    'Channelling...',
    'Vibing...',
    'Concocting...',
    'Spelunking...',
    'Transmuting...',
    'Imagining...',
    'Pontificating...',
    'Whirring...',
    'Cogitating...',
    'Honking...',
    'Flibbertigibbeting...',
    'Noodling...',
    'Percolating...',
    'Ruminating...',
    'Simmering...',
    'Marinating...',
    'Fermenting...',
    'Gestating...',
    'Hatching...',
    'Brewing...',
    'Steeping...',
    'Contemplating...',
    'Musing...',
    'Pondering...',
    'Mulling...',
    'Daydreaming...',
    'Woolgathering...',
    'Dithering...',
    'Faffing...',
    'Puttering...',
    'Tinkering...',
    'Fiddling...',
    'Noodging...',
    'Finagling...',
    'Wrangling...',
    'Jiggling...',
    'Wiggling...',
    'Shimmying...',
    'Galumphing...',
    'Perambulating...',
    'Meandering...',
    'Traipsing...',
    'Moseying...',
    'Sauntering...',
    'Ambling...',
    'Pottering...',
    'Bumbling...',
    'Futzing...',
    'Schmalzing...',
    'Kerfuffling...',
    'Bamboozling...',
    'Discombobulating...',
    'Recombobulating...',
    'Unbefuddling...',
    'Defenestrating...',
    'Confabulating...',
    'Persnicketing...',
    'Flummoxing...',
    'Befuddling...',
    'Snorkeling...',
    'Yodeling...',
    'Zigzagging...',
    'Ricocheting...',
    'Somersaulting...',
    'Pirouetting...',
    'Canoodling...',
    'Schmoozing...',
    'Kibbitzing...',
    'Skedaddling...',
    'Scampering...',
    'Skittering...',
    'Sashaying...',
    'Swashbuckling...',
    'Oscillating...',
    'Undulating...',
    'Pulsating...',
    'Effervescing...',
    'Fizzing...',
    'Bubbling...',
    'Perplexing...',
    'Mystifying...',
    'Enchanting...',
    'Bewitching...',
    'Beguiling...',
    'Mesmerizing...',
    'Bedazzling...',
    'Sparkling...',
    'Glittering...',
    'Scintillating...',
    'Coruscating...',
    'Phosphorescing...',
    'Luminescing...',
    'Sublimating...',
    'Synthesizing...',
    'Amalgamating...',
    'Procrastinating...',
    'Dillydallying...',
    'Lollygagging...',
    'Dawdling...',
    'Malingering...',
    'Skulking...',
    'Lurking...',
    'Sleuthing...',
    'Rummaging...',
    'Fossicking...',
    'Foraging...',
    'Scavenging...',
    'Absquatulating...',
    'Vamoosing...',
    'Absconding...',
    'Grooving...',
    'Jamming...',
    'Improvising...',
    'Extemporizing...',
    'Freestyling...',
    'Frolicking...',
    'Gamboling...',
    'Blorping...',
    'Flonking...',
    'Snurfling...',
    'Whomping...',
    'Zorping...',
    'Biffing...',
    'Splunging...',
    'Thwacking...',
    'Gonkulating...',
    'Splorfing...',
    'Wibbling...',
    'Wobbling...',
    'Squonking...',
    'Plonking...',
    'Bonking...',
    'Zonking...',
    'Flumping...',
    'Clomping...',
    'Squelching...',
    'Schlurping...',
    'Glurping...',
    'Burbling...',
    'Gurgling...',
    'Splooshing...',
    'Whooshing...',
    'Swooshing...',
    'Kerplunking...',
    'Thunking...',
    'Clunking...',
    'Clanking...',
    'Rattling...',
    'Jostling...',
    'Rustling...',
    'Bustling...',
    'Hustling...',
    'Miffing...',
    'Boffing...',
    'Snazzifying...',
    'Pizzazzing...',
    'Razzmatazzing...',
    'Bedoodling...',
    'Doodling...',
    'Scribbling...',
    'Squiggling...',
    'Wriggling...',
    'Niggling...',
    'Higgling...',
    'Piggling...',
    'Figgling...',
    'Gibbering...',
    'Jabbering...',
    'Blathering...',
    'Blithering...',
    'Withering...',
    'Slithering...',
    'Tethering...',
    'Feathering...',
    'Weathering...',
    'Leathering...',
    'Heathering...',
    'Smoldering...',
    'Moldering...',
    'Shouldering...',
    'Bouldering...',
    'Tottering...',
    'Teetering...',
    'Tittering...',
    'Flittering...',
    'Jittering...',
    'Frittering...',
    'Twittering...',
    'Nattering...',
    'Chattering...',
    'Clattering...',
    'Splattering...',
    'Battering...',
    'Scattering...',
    'Shattering...',
    'Flattering...',
    'Pattering...',
    'Tattering...',
    'Mattering...',
    'Yammering...',
    'Hammering...',
    'Stammering...',
    'Clamoring...',
    'Glamoring...',
    'Enamoring...',
    'Shimmering...',
    'Glimmering...',
    'Brimming...',
    'Skimming...',
    'Trimming...',
    'Primming...',
    'Whimming...',
    'Humming...',
    'Strumming...',
    'Thrumming...',
    'Drumming...',
    'Plumbing...',
    'Thumbing...',
    'Numbing...',
    'Fumbling...',
    'Grumbling...',
    'Mumbling...',
    'Rumbling...',
    'Stumbling...',
    'Tumbling...',
    'Crumbling...',
    'Jumbling...',
    'Humbling...',
    'Bungling...',
    'Jungling...',
    'Mangling...',
    'Wangling...',
    'Dangling...',
    'Tangling...',
    'Jangling...',
    'Angling...',
    'Struggling...',
    'Mingling...',
    'Tingling...',
    'Jingling...',
    'Singling...',
    'Ringling...',
    'Kingling...',
] as const

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

/** Pick a random whimsical message for the active turn. */
function pickRandomMessage(): string {
    return WORKING_MESSAGES[Math.floor(Math.random() * WORKING_MESSAGES.length)]
}

// -----------------------------------------------------------------------------
// Extension entry point
// -----------------------------------------------------------------------------

/**
 * Replace Pi's default working message with a random short whimsical phrase
 * while the agent is streaming, then restore the default message at the end of
 * the turn.
 */
export default function (pi: ExtensionAPI) {
    pi.on('turn_start', async (_event, ctx) => {
        ctx.ui.setWorkingMessage(pickRandomMessage())
    })

    pi.on('turn_end', async (_event, ctx) => {
        ctx.ui.setWorkingMessage()
    })
}
